# -*- coding: utf-8 -*-
"""PINEBI-0: the coverage CSV must stay reproducible from its classifier.

`docs/gen_pine_builtin_coverage.py` says in its own docstring that "the
classifier IS the artifact -- a changed count is not a finding, but a changed
VERDICT is". This makes that promise executable.

It exists because the promise was broken once, in a way that was invisible until
someone re-ran the script: PINEBI-1a landed the 18 primitives into
`pandas_ta.utils`, `classify()` consulted `equivalent()` before its `PRIMITIVES`
check, and fourteen rows silently flipped from `port - primitive` to `have` --
collapsing the split into two buckets and invalidating the CSV the four
downstream tasks are scoped from. The figures are deliberately NOT retyped
here: this docstring was itself one of the three places the split went
stale, and `test_no_other_document_retypes_the_split` now scans this file
along with every document in the fork. The fix was to make `PRIMITIVES`
outrank a namespace match; this test is the guard.

The corpus test is skipped when `docs/pine/` is absent — it is untracked by design
(2,211 files, 46MB, 912 of them MPL-2.0 © TradingView), so it exists on a
working checkout and not in CI. The other guards read the committed CSV and run
everywhere.
"""
import collections
import csv
import io
import os
import re
import subprocess
import sys

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
_FORK = os.path.dirname(_HERE)
DOCS = os.path.join(_FORK, "docs")
CSV = os.path.join(DOCS, "pine_builtin_coverage.csv")
GEN = os.path.join(DOCS, "gen_pine_builtin_coverage.py")
CORPUS = os.path.join(DOCS, "pine")

# One definition of "a verdict-count claim", used by both split guards. It was
# inline in a single test; two tests reading the same shape must not drift.
TABLE_ROW = r"^\s*\|\s*`([A-Za-z0-9/ '\-]+)`[^|]*\|\s*(\d+)\s*\|\s*$"
NAMELESS_SPLIT = r"\b\d+(?:/\d+){4,}\b"

VERDICTS = {
    "have", "port", "port - primitive", "port - alternate impl",
    "port - blocked on data", "n/a - not a Pine built-in",
    "n/a - not worth a primitive", "n/a - never called live in the corpus",
}


def _rows():
    # NOT a skip. The CSV is a committed artifact that four task scopes are cut
    # from; if it is missing, the guards below would evaporate into skips and a
    # clone would report green while checking nothing. It was ignored by
    # `.gitignore`'s blanket `*.csv` until 2026-09-07, so this failed silently
    # for every reader but the author.
    assert os.path.exists(CSV), (
        f"{CSV} is missing. It is generated by docs/gen_pine_builtin_coverage.py "
        f"and MUST be committed -- see the `!docs/pine_builtin_coverage.csv` "
        f"line in .gitignore."
    )
    with open(CSV, encoding="utf8") as fh:
        return list(csv.DictReader(fh))


def test_every_row_has_a_known_verdict():
    """PINEBI-0's acceptance criterion: every function classified, none blank."""
    rows = _rows()
    assert rows, "the CSV is empty"
    unknown = sorted({r["verdict"] for r in rows} - VERDICTS)
    assert unknown == [], f"unrecognised verdicts: {unknown}"
    blank = [r["name"] for r in rows if not r["name"] or not r["verdict"]]
    assert blank == [], blank


def test_primitives_stay_primitives_after_they_land():
    """The exact regression that broke reproducibility once.

    All 18 are importable from `pandas_ta` now, so a classifier that checks the
    namespace before its own PRIMITIVES list calls them `have` and quietly
    retires the task that is supposed to produce them.
    """
    rows = {r["name"]: r for r in _rows()}
    landed = [n for n in ("highest", "lowest", "barssince", "valuewhen",
                          "percentrank", "pivothigh", "pivotlow", "cum")
              if n in rows]
    assert landed, "expected the core primitives in the CSV"
    for name in landed:
        assert rows[name]["verdict"] == "port - primitive", (
            f"{name} is classified {rows[name]['verdict']!r}; landing a "
            f"primitive must not reclassify it"
        )


@pytest.mark.skipif(not os.path.isdir(CORPUS),
                    reason="docs/pine corpus is untracked by design (licence)")
def test_regenerating_reproduces_the_committed_csv(tmp_path):
    """Re-run the classifier; the verdict column must not move.

    Counts may drift with the corpus and that is explicitly allowed. Verdicts
    may not: they are what the -1a..-1e scopes are cut from.
    """
    out = tmp_path / "regenerated.csv"
    proc = subprocess.run([sys.executable, GEN, str(out)],
                          capture_output=True, text=True, cwd=_FORK)
    assert proc.returncode == 0, proc.stderr[-2000:]

    with open(out, encoding="utf8") as fh:
        fresh = {r["name"]: r["verdict"] for r in csv.DictReader(fh)}
    committed = {r["name"]: r["verdict"] for r in _rows()}

    moved = {n: (committed[n], fresh[n]) for n in committed.keys() & fresh.keys()
             if committed[n] != fresh[n]}
    assert moved == {}, f"verdicts changed on re-run: {moved}"
    assert committed.keys() == fresh.keys(), (
        f"row set changed: only-committed={sorted(committed.keys() - fresh.keys())}, "
        f"only-fresh={sorted(fresh.keys() - committed.keys())}"
    )


def _load_classifier():
    """Import `classify` from the generator without running it."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("_pine_cov_gen", GEN)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize("name,clean,lib,exports,expected", [
    # A sample of the eighteen that silently flipped once PINEBI-1a landed.
    ("highest", 332, 8, set(), "port - primitive"),
    ("lowest", 306, 8, set(), "port - primitive"),
    ("pivothigh", 229, 6, set(), "port - primitive"),
    ("barssince", 56, 2, set(), "port - primitive"),
    ("cum", 36, 1, set(), "port - primitive"),
    ("percentrank", 27, 0, set(), "port - primitive"),
    # tier-2 primitives, reachable only through the library
    ("highestSince", 0, 1, {"highestSince"}, "port - primitive"),
    # the all-time extremes, mislabelled "not a built-in" in round 1
    ("max", 3, 0, set(), "port - primitive"),
    ("min", 1, 0, set(), "port - primitive"),
    ("sum", 3, 0, set(), "n/a - never called live in the corpus"),
    # a genuine `have` must still resolve
    ("sma", 677, 0, set(), "have"),
    # and the other verdicts must not drift
    ("requestVolumeDelta", 0, 3, {"requestVolumeDelta"}, "port - blocked on data"),
    ("changePercent", 0, 0, {"changePercent"}, "n/a - not worth a primitive"),
    ("covariance", 1, 0, set(), "n/a - not a Pine built-in"),
    ("frama", 0, 0, {"frama"}, "port"),
])
def test_classify_is_stable_without_the_corpus(name, clean, lib, exports, expected):
    """`classify` is a pure function of four scalars -- guard it directly.

    The regeneration test above needs the 46MB untracked corpus and skips
    everywhere else, so on any other machine it protects nothing. This does not:
    reverting the PRIMITIVES-before-equivalent ordering flips every
    `port - primitive` row here to `have`, and this test fails.
    """
    gen = _load_classifier()
    assert gen.classify(name, clean, lib, exports)[1] == expected


@pytest.mark.parametrize("name,expected_shape", [
    ("max", "all-time"),
    ("min", "all-time"),
    ("cum", "all-time"),
    ("pivot_point_levels", "period-anchored"),
])
def test_non_rolling_primitives_are_not_described_as_rolling(name, expected_shape):
    """The note column is part of the artifact, and it shipped the wrong word.

    `classify()` used one hardcoded "rolling primitive" note for EVERY
    primitive. Round 3 caught it on `max`/`min`; the patch special-cased those
    two names and left `cum` (no length, running total) and
    `pivot_point_levels` (period-anchored) still calling themselves rolling in
    the CSV that the -1b..-1e scopes are read from. The note is now driven by a
    shape map, so this parametrizes over every non-rolling primitive.
    """
    gen = _load_classifier()
    note = gen.classify(name, 3, 0, set())[2]
    # The generic label, not the substring: `pivot_point_levels`' own note
    # legitimately reads "no rolling window".
    assert "rolling primitive" not in note, note
    assert expected_shape in note


def test_kcw_is_covered_by_its_own_port_and_not_by_an_alias_to_kc():
    """`pandas_ta.kc` ships the Keltner bands, not the Keltner WIDTH.

    HISTORY, kept because the failure mode outlived the bug: an alias to `kc`
    marked this `have` and silently deleted a real port. The sibling
    `bbw -> bbands` is correct only because `bbands` does emit `BBB_`; the two
    cases were never checked separately.

    `kcw` is now genuinely ported (PINEBI-1b tranche 1), so the assertion
    flips: it must be `have`, and it must be `have` because a real `ta.kcw`
    exists emitting a WIDTH column -- not because something aliased it back to
    the band function. Both halves are checked, because only the second one
    would have caught the original bug.
    """
    import pandas_ta as _ta
    gen = _load_classifier()
    verdict = gen.classify("kcw", 1, 0, set())[1]
    assert verdict == "have", "kcw is ported; the classifier should see it"

    assert callable(getattr(_ta, "kcw", None)), "no real ta.kcw"
    assert _ta.kcw is not _ta.kc, "kcw must not be an alias to kc"

    import numpy as _np
    from pandas import Series as _S
    n = 200
    rng = _np.random.default_rng(0)
    c = _S(100 * _np.exp(_np.cumsum(rng.normal(0, 0.01, n))))
    out = _ta.kcw(c * 1.01, c * 0.99, c)
    assert out is not None and out.ndim == 1, "kcw must emit one width column"
    # The width is a RATIO: scale every price and it does not move. A band
    # level would.
    out8 = _ta.kcw(c * 8 * 1.01, c * 8 * 0.99, c * 8)
    m = out.notna() & out8.notna()
    assert float((out[m] - out8[m]).abs().max()) == 0.0,         "kcw is not scale-free, so it is returning a level, not a width"


def test_every_tier2_have_row_was_docstring_audited():
    """A tier-2 `have` row must be backed by a recorded comparison.

    There used to be a second hand-maintained list here, `DOCSTRING_AUDITED`,
    duplicating the generator's own `AUDITED` map with nothing keeping them in
    step -- and 13 of its names had been certified on the library's one-line
    `@function` summary alone. Round 7 showed what that is worth: `trima`,
    `stc`, `aroon` and `kvo` were all on such a list and all diverge. There is
    now one source of truth, `gen.AUDITED`, and it stores evidence rather than
    names.
    """
    gen = _load_classifier()
    tier2_have = {r["name"] for r in _rows()
                  if r["verdict"] == "have"
                  and r["in_tradingview_ta_library"] == "1"}
    unaudited = sorted(tier2_have - set(gen.AUDITED))

    # Not an assertion that the backlog is empty: it is not, and saying
    # otherwise is the defect this whole thread of findings is about. What is
    # asserted is that the CSV DECLARES each one.
    for name in unaudited:
        row = next(r for r in _rows() if r["name"] == name)
        assert row["audited"] == "no", (
            f"{name} is not in gen.AUDITED but the CSV does not say so"
        )


# The one document allowed to state the verdict split. Everything else points
# at it. See `test_no_other_document_retypes_the_split`.
SPLIT_SOURCE = "TODO.md"

# A line carrying this marker may quote a wrong split on purpose -- review
# records narrate the numbers that WERE wrong, and "correcting" those would
# destroy the record. The marker makes deliberately-stale a declaration rather
# than an oversight.
STALE_BY_DESIGN = "<!--stale-by-design-->"


def _documents():
    """Every prose file in the fork, plus this guard's own source.

    Discovered, not enumerated. Round 8 fixed the three known copies of the
    stale split and left the class open; a hard-coded list of three files is
    the same escape route one level up.
    """
    found = []
    for root, dirs, files in os.walk(_FORK):
        dirs[:] = [d for d in dirs if d not in {
            ".git", "pine", "__pycache__", ".pytest_cache", "build", "dist",
        }]
        for name in files:
            if name.endswith(".md"):
                found.append(os.path.join(root, name))
    found.append(os.path.abspath(__file__))
    return found


def _quoted_counts(text, verdicts):
    """Verdict-count claims, in the two shapes documents actually use.

    Shape A -- a markdown table row: ``| `have` | 55 |``.
    Shape B -- a backticked span: ``have 75 / port - primitive 2``  <!--stale-by-design-->. Requiring
    the span is what keeps ordinary English ("we have 3 tests") out of the scan
    while still catching a real claim.
    """
    rows = re.findall(TABLE_ROW, text, re.M)
    found = [(name.strip(), int(n)) for name, n in rows]
    for span in re.findall(r"`([^`\n]+)`", text):
        for verdict in sorted(verdicts, key=len, reverse=True):
            # \b BEFORE the verdict too: without it "report 25" matched the
            # verdict `port`, and `docs/CandlePatternShortlist.md` was accused
            # of retyping the split by a probe banner reading "functions
            # report 25". A guard with a false positive gets switched off.
            for match in re.finditer(
                    r"\b" + re.escape(verdict) + r"\s+(\d+)\b", span):
                found.append((verdict, int(match.group(1))))
    return found


def test_no_other_document_retypes_the_split():
    """MAJOR (round 9): exactly ONE document may state the split.

    The previous guard read `TODO.md` only, so the very file written to stop
    the split going stale carried a stale split in its own docstring -- three
    positions wrong, summing to 108 against 107 rows. Correcting that fixes the
    instance. This closes the class: any document naming a verdict and a
    number, anywhere in the fork, must either BE the single asserted source or
    declare itself deliberately historical.
    """
    actual = collections.Counter(r["verdict"] for r in _rows())
    source = os.path.normcase(os.path.join(_FORK, SPLIT_SOURCE))

    offenders = {}
    for path in _documents():
        if os.path.normcase(path) == source:
            continue
        text = io.open(path, encoding="utf8").read()
        claims = _quoted_counts(text, set(actual))
        # A nameless split -- `55/18/16/9/4/2/2/1` <!--stale-by-design--> -- is the shape that went
        # stale in this file. Five or more slash-joined numbers is specific
        # enough to mean a split and nothing else.
        claims += [(m.group(0), None) for m in re.finditer(NAMELESS_SPLIT, text)]
        if not claims:
            continue
        lines = text.splitlines()
        undeclared = [c for c in claims
                      if not any(STALE_BY_DESIGN in ln and str(c[0]) in ln
                                 for ln in lines)]
        if undeclared:
            offenders[os.path.relpath(path, _FORK)] = sorted(
                set(undeclared), key=str)

    assert offenders == {}, (
        f"these documents retype the verdict split instead of pointing at "
        f"{SPLIT_SOURCE}: {offenders}. Either delete the numbers and cite the "
        f"asserted table, or mark the line {STALE_BY_DESIGN} if it quotes a "
        f"historically wrong value on purpose."
    )


def test_the_docs_quote_the_csvs_actual_split():
    """Numbers in prose are asserted, not retyped.

    The verdict split was hand-written into three documents and went stale in
    all three across four review rounds -- the repo's dominant defect, per
    CLAUDE.md. `TODO.md` is now the single place allowed to state it, and this
    asserts it against the CSV; `test_no_other_document_retypes_the_split`
    keeps it single.
    """
    actual = collections.Counter(r["verdict"] for r in _rows())
    todo = os.path.join(_FORK, SPLIT_SOURCE)
    assert os.path.exists(todo), (
        f"{SPLIT_SOURCE} is the declared home of the verdict split and is "
        f"missing. This was a pytest.skip, which is how a guard evaporates."
    )
    text = io.open(todo, encoding="utf8").read()

    # Rows of the PINEBI-0 verdict table: `| \`verdict\` (→ -1x) | n |`.
    # The character class must admit capitals: the first version was
    # lowercase-only and silently skipped `n/a - not a Pine built-in`, so that
    # row's count was unasserted on the day the guard shipped.
    rows = re.findall(TABLE_ROW, text, re.M)
    # Keep the raw LIST. The previous version built a dict comprehension, so two
    # tables with contradictory counts collapsed to whichever came last -- which
    # is exactly the stale-duplicate-table defect this guard exists for, and it
    # was "fixed" by deleting the duplicate rather than by trapping duplicates.
    named = [(name.strip(), int(n)) for name, n in rows if name.strip() in actual]

    seen = collections.Counter(name for name, _ in named)
    duplicated = sorted(n for n, c in seen.items() if c > 1)
    assert duplicated == [], (
        f"verdict rows appearing more than once in TODO.md: {duplicated}. Two "
        f"tables mean one of them is stale; keep a single table."
    )

    quoted = dict(named)

    # Real set equality, in BOTH directions. The previous version filtered with
    # `if name in actual`, so a row naming a verdict the CSV no longer has was
    # silently discarded and the reverse containment could never fail.
    missing = sorted(set(actual) - set(quoted))
    assert missing == [], (
        f"verdicts in the CSV with no row in TODO.md's table: {missing}. "
        f"Add them, or the table is no longer the split it claims to be."
    )
    unknown = sorted({name.strip() for name, _ in rows}
                     - set(actual) - {"verdict"})
    assert unknown == [], (
        f"TODO.md's table names verdicts the CSV does not have: {unknown}"
    )

    wrong = {k: (v, actual[k]) for k, v in quoted.items() if v != actual[k]}
    assert wrong == {}, (
        f"TODO.md quotes counts the CSV does not support "
        f"{{verdict: (quoted, actual)}}: {wrong}"
    )


def test_every_map_entry_is_reachable():
    """No dead entries in ANY name-keyed collection the classifier defines.

    The previous version hard-coded seven maps and the classifier had ten -- the
    omitted one being `AUDITED`, added by the round that wrote the test. That is
    the same escape route as `adx`: a guard that closes a class over an
    enumerated list rather than over the population. This discovers them.
    """
    gen = _load_classifier()
    names = {r["name"] for r in _rows()}

    # Collections that are keyed by something other than a Pine name.
    # Empty, and it must stay honest: the previous value was {"SHAPE_UNUSED"},
    # an attribute the classifier has never defined. A typo'd or outdated
    # exclusion is a hole opened in advance -- it excuses a map that does not
    # exist today and would silently excuse one appearing under that name
    # tomorrow. So every exclusion must name something real.
    NOT_NAME_KEYED = set()
    phantom = sorted(n for n in NOT_NAME_KEYED if not hasattr(gen, n))
    assert phantom == [], (
        f"NOT_NAME_KEYED excludes attributes the classifier does not define: "
        f"{phantom}. Delete them, or the exclusion is a pre-opened hole."
    )

    discovered = {}
    for attr in dir(gen):
        if attr.startswith("_") or attr in NOT_NAME_KEYED or not attr.isupper():
            continue
        value = getattr(gen, attr)
        if isinstance(value, (dict, set, frozenset)) and value and all(
                isinstance(k, str) for k in value):
            discovered[attr] = set(value)

    assert len(discovered) >= 10, (
        f"expected at least the ten name-keyed collections, found "
        f"{sorted(discovered)}"
    )

    for map_name, keys in sorted(discovered.items()):
        dead = sorted(keys - names)
        assert dead == [], (
            f"{map_name} has entries that match no row in the CSV: {dead}"
        )

    # A caveat that is never emitted is worse than no caveat: it reads as a
    # recorded warning while the artifact carries none.
    rows_by_name = {r["name"]: r for r in _rows()}
    for name, caveat in gen.SEMANTIC_CAVEAT.items():
        note = rows_by_name[name]["note"]
        assert caveat[:40] in note, (
            f"SEMANTIC_CAVEAT[{name!r}] never reaches the CSV -- the row's "
            f"verdict is {rows_by_name[name]['verdict']!r} and its note is "
            f"{note[:80]!r}"
        )


def test_have_rows_declare_whether_anyone_checked_them():
    """`have` is a claim of equivalence; the CSV must say who verified it.

    Three `have` rows turned out to be different indicators (`kcw`, `dm`) or
    inexpressible calls (`cagr`), each found only when someone finally read the
    source. The `audited` column records which rows have been compared, so an
    unchecked row reads as unchecked rather than as an all-clear.
    """
    for row in _rows():
        if row["verdict"] == "have":
            assert row["audited"] in {"yes", "no"}, row
        else:
            assert row["audited"] == "n/a", row

    unaudited = sorted(r["name"] for r in _rows()
                       if r["verdict"] == "have" and r["audited"] == "no")
    # PINEBI-0b certifies by measuring each `have` against an independent
    # implementation of the Pine v6 formula. The counts here are NOT retyped
    # into prose any more: an earlier version of this comment said "20 of the
    # 40" long after the real figures had moved, and a stale comment on a
    # ratchet is how the ratchet stops meaning anything. The rest stay unaudited ON PURPOSE
    # and every one must SAY WHY -- silence is what let five wrong `have`
    # verdicts ship. A shrinking backlog is progress; an unexplained one is not.
    # A row carrying a measured SEMANTIC_CAVEAT has stated its reason in the
    # strongest available form -- `hma` and `cmo` diverge from Pine and the
    # caveat says by how much. That is not silence.
    gen = _load_classifier()
    silent = [r["name"] for r in _rows()
              if r["verdict"] == "have" and r["audited"] == "no"
              and "PINEBI-0b not certified:" not in r["note"]
              and r["name"] not in gen.SEMANTIC_CAVEAT]
    assert silent == [], (
        f"unaudited `have` rows with no stated reason: {silent}. Add them to "
        f"NOT_CERTIFIED in docs/audit_pine_have_rows.py with the reason."
    )
    # Count the CERTIFICATIONS, not the backlog. The backlog grew when `hma`
    # and `cmo` moved from "certified" to "measured divergence with a caveat"
    # -- a stronger result, not a regression, and a ceiling on the backlog
    # would have punished it.
    #
    # The floor sits two below the established count so that same move stays
    # possible; it is a ratchet, so raise it when the count rises, never lower
    # it to make a red suite green.
    CERTIFIED_FLOOR = 28              # established 30 of 55 `have` rows
    certified = [r["name"] for r in _rows()
                 if r["verdict"] == "have" and r["audited"] == "yes"]
    assert len(certified) >= CERTIFIED_FLOOR, (
        f"certifications fell to {len(certified)}; PINEBI-0b established "
        f"{CERTIFIED_FLOOR}+ by measurement against an independent Pine v6 "
        f"implementation and that floor should only rise"
    )


@pytest.mark.parametrize("name,caveat_marker", [
    ("crossunder", "above=False"),
    ("cross", "EITHER direction"),
    ("swma", "length=4"),
    ("supertrend", "INVERTED"),
    ("eom", "1e4"),
    ("change", "defaults to 10"),
    ("sar", "PSARl"),
])
def test_known_semantic_divergences_are_recorded_in_the_artifact(name, caveat_marker):
    """Each `have` that is not a drop-in says so where the porter will read it.

    These were found by comparing implementations, not names: `pandas_ta.cross`
    is upward-only, `pandas_ta.swma` defaults to length 10 against Pine's fixed
    4-bar kernel, `supertrend`'s direction sign is inverted against the
    library's, `eom`'s divisor differs by 1e4.
    """
    rows = {r["name"]: r for r in _rows()}
    assert name in rows, f"{name} is not in the CSV"
    assert caveat_marker in rows[name]["note"], rows[name]["note"]


def test_audited_rows_carry_their_evidence():
    """`audited=yes` must cite a line that actually carries the claim.

    Three rounds of escalation on one point. Round 6 required a NAME, and four
    of twenty-nine names were divergent. Round 7 required a `file:line`-SHAPED
    string, and never opened the file -- so seven of fifteen receipts pointed at
    the wrong line and one (`variance`) asserted a divergence that does not
    exist, being `stdev`'s caveat pasted across without running the code.

    This opens the file. Every `<path>:<n>` in the receipt must resolve, `n`
    must be in range, and the receipt's backticked token must appear within two
    lines of `n`. A fabricated citation now fails.
    """
    for row in _rows():
        if row["audited"] != "yes":
            assert row["audit_evidence"] == "", (
                f"{row['name']}: evidence recorded but audited={row['audited']}"
            )
            continue

        evidence = row["audit_evidence"]
        assert len(evidence) > 30, f"{row['name']}: evidence too thin: {evidence!r}"

        # PAIRED form: `path:line` immediately followed by the backticked
        # token that carries the claim. An earlier version collected citations
        # and tokens separately and asked `any(token in line)`, which a
        # deliberately wrong-but-in-range citation survived because an
        # incidental backticked word elsewhere in the prose ("unlike
        # `variance`") happened to appear at the wrong line.
        pairs = re.findall(
            r"([\w/.-]+\.(?:py|pine)):(\d+)[\s\-–—]*`([^`]+)`", evidence)
        assert pairs, (
            f"{row['name']}: evidence has no `path:line `token`` pair, so "
            f"there is nothing to check -- {evidence!r}"
        )

        checked_a_repo_file = False
        for path, lineno, token in pairs:
            full = os.path.join(_FORK, path)
            if not os.path.exists(full):          # the library .pine lives in docs/pine
                full = os.path.join(DOCS, "pine", os.path.basename(path))
            assert os.path.exists(full), (
                f"{row['name']}: the receipt cites {path}, which resolves to no "
                f"file in this repo. A citation nobody can open is not evidence."
            )
            checked_a_repo_file = True
            lines = io.open(full, encoding="utf8", errors="replace").read().splitlines()
            n = int(lineno)
            assert 1 <= n <= len(lines), (
                f"{row['name']}: {path}:{n} is out of range (file has "
                f"{len(lines)} lines)"
            )
            assert token in lines[n - 1], (
                f"{row['name']}: the receipt's token {token!r} is not ON "
                f"{path}:{n}. The citation does not carry the claim:"
                f"{chr(10)}  {lines[n - 1].strip()}"
            )
        assert checked_a_repo_file, (
            f"{row['name']}: no cited path resolved in the repo -- {evidence!r}"
        )


def test_divergent_rows_are_both_audited_and_caveated():
    """A comparison that found a divergence must show it in the note.

    `supertrend`, `trima`, `aroon` and `kvo` were all marked audited with no
    caveat while diverging. If the evidence says "Caveated", the note has to
    carry one.
    """
    gen = _load_classifier()
    for row in _rows():
        if row["audited"] == "yes" and "Caveated" in row["audit_evidence"]:
            assert row["name"] in gen.SEMANTIC_CAVEAT, (
                f"{row['name']}: evidence claims a caveat, none in SEMANTIC_CAVEAT"
            )
            assert "⚠" in row["note"], (
                f"{row['name']}: caveat never reached the note: {row['note'][:80]!r}"
            )


@pytest.mark.parametrize("verdict,block,next_block", [
    ("port", "PINEBI-1b", "PINEBI-1c"),
    ("port - alternate impl", "PINEBI-1c", "PINEBI-1d"),
])
def test_every_scoped_row_is_named_in_its_task(verdict, block, next_block):
    """A verdict routes a row to a task; the task must actually list it.

    `stc` was reported as "scoped into PINEBI-1b" for a whole round while
    existing only as the string `; PINEBI-1b` inside a CSV note. The split guard
    could not see it: that test reads markdown TABLES, and a scope written in
    prose is unguarded. This reads the task block itself.
    """
    todo = os.path.join(_FORK, "TODO.md")
    if not os.path.exists(todo):
        pytest.skip("TODO.md missing")
    text = io.open(todo, encoding="utf8").read()
    # Anchor on the task BLOCK, not the first bare mention. `text.index(block)`
    # matched the ACTIVE band's one-line summary ("**PINEBI-1c/-1d/-1e**"),
    # where the next tag follows immediately, so `body` was a ten-character
    # slice with no `ROWS:` line and the guard reported a real, present
    # enumeration as missing. Search for the thing, not the name -- the same
    # lesson the altrepo scanners keep teaching.
    def _block_start(tag, frm=0):
        for marker in (f"**{tag} —", f"**{tag} -", f"**{tag}"):
            i = text.find(marker, frm)
            if i != -1:
                return i
        return text.index(tag, frm)

    start = _block_start(block)
    body = text[start:_block_start(next_block, start)]

    expected = sorted(r["name"] for r in _rows() if r["verdict"] == verdict)

    # The ENUMERATION line, not "mentioned somewhere in the block". A prose
    # mention elsewhere in the same task satisfied the looser check during
    # mutation testing, so deleting a name from the list it is actually ported
    # from would have passed.
    # The scope's rows are declared on an explicit `ROWS:` line. Heuristics
    # failed twice: reading one line missed `stochFull`/`stochRsi` on a
    # continuation, and reading the whole region passed a deleted `stc` because
    # a prose sentence in the same region happened to mention it. A marker the
    # guard and the human both read removes the guessing.
    marker = [l for l in body.splitlines() if l.strip().startswith("ROWS:")]
    assert len(marker) == 1, (
        f"{block} must declare its rows on exactly one `ROWS:` line, found "
        f"{len(marker)}"
    )
    enumeration = set(re.findall(r"`([A-Za-z_][A-Za-z0-9_]*)`", marker[0]))

    missing = [n for n in expected if n not in enumeration]
    # Only flag names that belong to ANOTHER verdict bucket -- prose in the
    # region legitimately mentions functions and task ids.
    routed_elsewhere = {r["name"]: r["verdict"] for r in _rows()}
    extra = sorted(n for n in enumeration - set(expected)
                   if routed_elsewhere.get(n, verdict) != verdict)
    assert missing == [], (
        f"{block}'s list omits {missing}, which the CSV routes to it. A task "
        f"that does not list a row will not port it."
    )
    assert extra == [], (
        f"{block}'s list names {extra}, which the CSV does not route to it"
    )

