# -*- coding: utf-8 -*-
"""Mechanical guard for the INDREF per-indicator pages in `docs/indicators/`.

WHY THIS FILE EXISTS.  The parent repo already has the post-mortem for
documentation that polices itself by asking nicely: `Backtesting/CLAUDE.md:77`
records that knowledge-base v1 died because "the bookkeeping was all by hand and
went stale faster than anyone could re-read it" -- one week of review produced a
count wrong by 13x and the same tally corrected in one file and left stale in
three siblings four separate times.  Its v2 rule is quoted there verbatim: **a
number that cannot be regenerated by a script does not go on a page.**
`Backtesting/CLAUDE.md:84` then records that v2's own guard,
`scripts/utils/verify_wiki.py`, DOES NOT EXIST -- so v2 is "v1 with better
intentions".  INDREF-1 will emit ~201 pages; a prose rule in `_TEMPLATE.md`
would be that mistake a third time.

THE UNIT OF COVERAGE IS A GROUP, AND EVERY GROUP DECLARES ITS COUNT
-------------------------------------------------------------------
Round-2 of this guard used SECTION-level coverage and it was too weak to be
worth running: one metrics row licensed every number in that section forever, so
`| fabricated sharpe | 1.87 | 2.99 |` inserted into an already-registered
section passed clean.  On pages where every section is registered by
construction -- which is what `_TEMPLATE.md` instructs -- that degrades to "did
the author write a table".

So the page is now cut into GROUPS, each with a stable anchor:

    §<section>#T<k>   the k-th markdown table in that section
    §<section>#P      everything else in that section (prose, bullets, quotes)

Every group carrying at least one provenance-bearing number must have a metrics
row whose label contains its anchor AND declares `n=<count>` matching the number
of such numbers the guard counts in it.  Adding a number to a covered table --
the exact defect section-level coverage missed -- changes the count and fails.
Deleting one fails too, which is deliberate: a vanished number means a vanished
claim, and the metrics block should not keep asserting it.

PROSE IS SCANNED, NOT JUST TABLES.  Round 2 scanned only lines starting with
`|`, which meant the machine-filled half of a page was policed and the
human-invented half -- the "what it measures" and "ML-suitability" prose, where
fabrication actually happens -- was invisible.  A bullet reading
`measured Sharpe **2.41**, rho = 0.9912` passed clean.  Prose now lands in the
`#P` group of its section under the same rule.

EXEMPTIONS, per number, in order:
  (a) the enclosing cell/line carries the literal STUB token;
  (b) the enclosing cell/line carries an inline artifact citation.
Anything else must be counted in its group's metrics row.

METRICS ROWS ARE THEMSELVES CHECKED.  Each must cite an artifact, a `tests/...`
anchor, or the literal `DERIVED` class, and each must name a group that actually
exists -- an invented row for a section that carries no such group is an orphan
and fails, so a metrics block cannot be padded to look thorough.

WHAT IT DELIBERATELY DOES NOT DO
--------------------------------
* It does NOT check that a cited artifact exists.  Overlap CSVs live under the
  parent repo's gitignored `backtest_results/`, are routinely cleaned, and a page
  that honestly records "quoted, artifact missing, here is how to re-run it" is
  correct.  Attribution is checked; resolution is not.
* It does NOT check that a value is CORRECT.  `n=<count>` catches an added or
  removed number, never a wrong one.  A page can still state 3.73 where 3.75 is
  true; only a reader or a re-run catches that.
* It does NOT match bare small integers ("89 frames", "L71", "33 cells").
  Flagging those would train authors to ignore the test.  A fabricated integer
  count therefore slips through unless it carries a decimal, a thousands
  separator, an exponent, or a percent sign.
"""
import io
import os
import re

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.normpath(os.path.join(HERE, "..", "docs", "indicators"))

#: The one accepted form for an unmeasured field.
STUB_RE = re.compile(r"STUB: not measured — fill from \S+")

METRICS_MARKER = "<!-- indref:metrics -->"

#: A number that carries a claim: decimal, thousands-separated integer,
#: scientific notation, or an integer percentage. Bare small integers are out --
#: see "WHAT IT DELIBERATELY DOES NOT DO".
NUMBER_RE = re.compile(
    r"(?<![\w.§])(?<!§\d)(?<!§\d\.)[-+±]?(?:"
    r"\d+\.?\d*[eE][-+]?\d+"          # 1.11e-14, 2e5
    r"|\d{1,3}(?:,\d{3})+"            # 404,066
    r"|\d+\.\d+"                      # 0.930462
    r"|\d+\s*%"                       # 87 %
    r")(?![\w])"
)

#: An inline artifact citation. A test anchor may be a line number or -- the
#: preferred form, see the header note about Python line numbers -- a `::name`
#: function anchor.
ARTIFACT_RE = re.compile(
    r"(?:[\w./\-]+\.(?:csv|py|pine|md|json)\b)"
    r"|(?:tests/test_[\w]+\.py(?:::[\w]+|:\d+))"
)

#: Accepted provenance classes in a metrics row's `@` cell.
PROV_CLASS_RE = re.compile(r"\bDERIVED\b|\bQUOTED\b")

SEP_RE = re.compile(r"^\|[\s:\-|]+\|$")
HEADING_RE = re.compile(r"^(#{2,4})\s+(.*)$")
ANCHOR_RE = re.compile(r"§(\d+(?:\.\d+)*)#(T\d+|P)")
COUNT_RE = re.compile(r"\bn=(\d+)\b")


def _pages():
    if not os.path.isdir(DOCS):
        return []
    return [os.path.join(DOCS, f) for f in sorted(os.listdir(DOCS))
            if f.endswith(".md") and not f.startswith("_")]


PAGES = _pages()
IDS = [os.path.basename(p) for p in PAGES]

if not PAGES:  # pragma: no cover
    pytestmark = pytest.mark.skip(reason="no docs/indicators/*.md pages yet")


def _read(path):
    return io.open(path, encoding="utf-8").read()


def _section_key(heading_text):
    m = re.match(r"(\d+(?:\.\d+)*)\.?\s", heading_text.strip())
    return m.group(1) if m else heading_text.strip().lower()[:24]


def _split(text):
    """(body, metrics_rows). The metrics block is excluded from the body scan by
    POSITION, not by membership -- a metrics row is not exempt from being a
    group, it simply is not part of one."""
    if METRICS_MARKER not in text:
        return text, None
    body, tail = text.split(METRICS_MARKER, 1)
    rows = []
    for ln in tail.splitlines():
        s = ln.strip()
        if s.startswith("#"):
            break            # the block ends at the next heading
        if s.startswith("|") and not SEP_RE.match(s):
            rows.append(s)
    return body, rows[1:] if len(rows) > 1 else []


def _groups(body):
    """{anchor: (count, [samples])} over the page body."""
    counts, samples = {}, {}
    # Content before the first H2 is section "0" so it gets a normal anchor.
    section, tbl_ord, in_tbl, in_fence = "0", 0, False, False

    def bump(anchor, frag):
        counts[anchor] = counts.get(anchor, 0) + 1
        samples.setdefault(anchor, []).append(frag[:60])

    for ln in body.splitlines():
        if ln.strip().startswith("```"):
            in_fence = not in_fence
            in_tbl = False
            continue
        if in_fence:
            continue
        h = HEADING_RE.match(ln)
        if h:
            section, tbl_ord, in_tbl = _section_key(h.group(2)), 0, False
            continue
        s = ln.strip()
        is_row = s.startswith("|")
        if is_row and not in_tbl:
            in_tbl, tbl_ord = True, tbl_ord + 1
        elif not is_row:
            in_tbl = False
        if SEP_RE.match(s):
            continue
        anchor = ("§%s#T%d" % (section, tbl_ord)) if is_row else ("§%s#P" % section)
        units = [c for c in s.strip("|").split("|")] if is_row else [s]
        for unit in units:
            if not NUMBER_RE.search(unit):
                continue
            if STUB_RE.search(unit) or ARTIFACT_RE.search(unit):
                continue
            for m in NUMBER_RE.finditer(unit):
                bump(anchor, m.group(0) + " … " + unit.strip())
    return counts, samples


def _declared(rows):
    """{anchor: summed n} from the metrics block.

    SEVERAL rows may name the same anchor and their counts SUM.  That is not a
    convenience: it is how one group gets split across provenance classes -- e.g.
    a measured row citing the CSV plus a DERIVED row for the numbers the author
    computed in-document from the cells above them.  Attributing an
    author-derived number to a missing artifact is precisely the defect these
    pages exist to prevent, so the format has to make the split expressible."""
    out = {}
    for r in rows or []:
        a = ANCHOR_RE.search(r)
        c = COUNT_RE.search(r)
        if a and c:
            k = "§%s#%s" % (a.group(1), a.group(2))
            out[k] = out.get(k, 0) + int(c.group(1))
    return out


# ------------------------------------------------------------------ tests


@pytest.mark.parametrize("path", PAGES, ids=IDS)
def test_every_page_has_a_metrics_block(path):
    _, rows = _split(_read(path))
    assert rows is not None, (
        f"{os.path.basename(path)} has no {METRICS_MARKER} block.")
    assert rows, f"{os.path.basename(path)}: metrics block is empty."


@pytest.mark.parametrize("path", PAGES, ids=IDS)
def test_every_metrics_row_cites_an_artifact(path):
    _, rows = _split(_read(path))
    bad = []
    for r in rows or []:
        cells = [c.strip() for c in r.strip("|").split("|")]
        if len(cells) < 3:
            bad.append((r, "fewer than 3 cells"))
            continue
        prov = cells[-1]
        if not prov.startswith("@"):
            bad.append((r, "last cell does not start with '@'"))
        elif not (ARTIFACT_RE.search(prov) or PROV_CLASS_RE.search(prov)
                  or "STUB:" in prov):
            bad.append((r, "no artifact path and no DERIVED/QUOTED class"))
    assert not bad, (
        f"{os.path.basename(path)}: unusable metrics rows:\n"
        + "\n".join(f"  {why}: {r}" for r, why in bad))


@pytest.mark.parametrize("path", PAGES, ids=IDS)
def test_every_metrics_row_declares_an_anchor_and_a_count(path):
    _, rows = _split(_read(path))
    bad = [r for r in (rows or [])
           if not (ANCHOR_RE.search(r) and COUNT_RE.search(r))]
    assert not bad, (
        f"{os.path.basename(path)}: metrics rows must carry a group anchor "
        f"(§<section>#T<k> or §<section>#P) and an n=<count>:\n  "
        + "\n  ".join(bad))


@pytest.mark.parametrize("path", PAGES, ids=IDS)
def test_no_orphan_metrics_row(path):
    body, rows = _split(_read(path))
    counts, _ = _groups(body)
    declared = _declared(rows)
    orphans = sorted(set(declared) - set(counts))
    assert not orphans, (
        f"{os.path.basename(path)}: metrics rows naming groups that carry no "
        f"provenance-bearing number (a padded block):\n  " + "\n  ".join(orphans))


@pytest.mark.parametrize("path", PAGES, ids=IDS)
def test_every_number_group_is_covered_with_a_matching_count(path):
    body, rows = _split(_read(path))
    counts, samples = _groups(body)
    declared = _declared(rows)

    missing, mismatched = [], []
    for anchor, n in sorted(counts.items()):
        if anchor not in declared:
            missing.append(f"{anchor}: {n} number(s), e.g. {samples[anchor][0]}")
        elif declared[anchor] != n:
            mismatched.append(
                f"{anchor}: page has {n}, metrics block declares "
                f"n={declared[anchor]}")

    assert not (missing or mismatched), (
        f"{os.path.basename(path)}: group coverage failed.\n"
        f"UNCOVERED GROUPS ({len(missing)}) — add a metrics row naming the "
        f"anchor with n=<count>, cite the artifact inline, or use the literal "
        f"'STUB: not measured — fill from <path>':\n  "
        + "\n  ".join(missing)
        + ("\n" if missing and mismatched else "")
        + (f"COUNT MISMATCHES ({len(mismatched)}) — a number was added to or "
           f"removed from a covered group:\n  " + "\n  ".join(mismatched)
           if mismatched else ""))


@pytest.mark.parametrize("path", PAGES, ids=IDS)
def test_stub_token_is_used_verbatim(path):
    text = _read(path)
    hits = []
    for pat, label in [(r"\bTBD\b", "TBD"), (r"\bFIXME\b", "FIXME"),
                       (r"<fill[^>]*>", "<fill...>"), (r"\bXXX\b", "XXX")]:
        hits += [f"{label} at offset {m.start()}" for m in re.finditer(pat, text)]
    assert not hits, (
        f"{os.path.basename(path)}: placeholder text that is not the INDREF "
        f"stub token. Use exactly 'STUB: not measured — fill from <path>'.\n  "
        + "\n  ".join(hits))

    for lineno, ln in enumerate(text.splitlines(), 1):
        s = ln.strip()
        if not s.startswith("|"):
            continue
        for cell in s.strip("|").split("|"):
            c = cell.strip()
            if re.fullmatch(r"(?i)(not measured|n/?a|unknown|\?\?\?)", c):
                pytest.fail(
                    f"{os.path.basename(path)}:{lineno}: bare '{c}' in a table "
                    f"cell. Use 'STUB: not measured — fill from <path>'.")
