# -*- coding: utf-8 -*-
from .alma import alma
from .dema import dema
from .ema import ema
from .ema_align import ema_align
from .fwma import fwma
from .hilo import hilo
from .hl2 import hl2
from .hlc3 import hlc3
from .hma import hma
from .hwma import hwma
from .jma import jma
from .kama import kama
from .ichimoku import ichimoku
from .ichimoku_ml import ichimoku_ml
from .linreg import linreg
from .linreg_channel import linreg_channel
from .ma import ma
from .mcgd import mcgd
from .midpoint import midpoint
from .mmar import mmar
from .midprice import midprice
from .ohlc4 import ohlc4
from .pwma import pwma
from .rainbow import rainbow
from .rma import rma
from .sinwma import sinwma
from .sma import sma
from .ssf import ssf
from .supertrend import supertrend
from .swma import swma
from .t3 import t3
from .tema import tema
from .trima import trima
from .vidya import vidya
from .vwap import vwap
from .vwma import vwma
from .wcp import wcp
from .wma import wma
from .zlma import zlma